Mode: production

System:
 Addr: 8080
 RouterPrefix: "/api"
 JwtKey: "test"
 ClientSignKey: ""

Redis:
  Addr: "redis:6379"
  Password: ""
  Db: 0

Mysql:
  Path: "mysql"
  Port: "3306"
  Config: "parseTime=True&loc=Local"
  DbName: "Accounting"
  Username: "hypnos"
  Password: "hypnos" 

ThirdParty:
  Ai:
    voice:
      api_key: "your_voice_api_key"
    ocr:
      api_key: "your_ocr_api_key"
    chat:
      api_key: "your_chat_api_key"